### ISSUE TITLE
Html style intellicense is not working appropriately

### ISSUE THREAD

**Issue by albertwoo** [alfonsogarciacaro/vscode-template-fsharp-highlight#10]
After typing style and press enter, the intelicense is popout correctly. But after input some values the intellicense will not popout for style again. But I can add other attributes like class etc.

It looks like the fsharp intellicense is taken over when I type stuff in the style attribute.

![html style not working](https://user-images.githubusercontent.com/8017681/145321711-88f930a0-96eb-4c93-8b80-1fb5dd594f0a.gif)

**Comment by alfonsogarciacaro** [comment]
Hmm, I cannot reproduce this. It's true that sometimes an F# tooltip appears but I usually press ESC to remove it and I can keep working normally. Not sure why the F# tooltip appears. The extension "hijacks" the completion provider and detects if you're in the middle of an interpolated string, in that case it creates a virtual document with the contents of the string (minus the holes) and asks VS Code to provide completion for that language. Not sure if the tooltip appears because this extension is not covering some specific case or it's just a glitch of the interaction with Ionide extension.

**Comment by albertwoo** [comment]
@alfonsogarciacaro can you let me know what version of ionide you are using?
I am using v5.10.2, and I tried on two computer and the bug can be reproduced.

**Comment by albertwoo** [comment]
I found if I change VSCode settings to：

```json
    "editor.quickSuggestions": {
        "strings": true
    }
```

Then it works as expected.
